### PR TITLE
Prefer supports select specific example

### PR DESCRIPTION
**Pull request by wcpan**
Make Prefer header supports selection for specific example

e.g.
curl -H "Prefer: status=200&example=success1" http://localhost:8000/users

### CODE REVIEW

**Comment by wcpan** [comment]
found a bug, close this PR.

**Comment by danielgtaylor** [comment]
This is a great idea! One comment though: I think the [HTTP Prefer Header](https://tools.ietf.org/html/rfc7240) has a slightly different format. Would you be willing up update to the official format?

**Comment by dsolonenko** [comment]
@wcpan great idea, exactly what I was looking for. Can you please update the PR?

**Comment by samit4me** [comment]
Any updates on this? This would be amazing.

**Comment by danielgtaylor** [comment]
Closing as I believe this is superseded by #55

**Pull request closed without merging**
