### PR TITLE
Generate response from schema examples

### PR DESCRIPTION
**Pull request by pruser**
This pull request is the first step towards generating responses from schema.

If schema example field exists, it is returned and send as response.
If there are no schema example, the examples of properties are inspected to build response.

### CODE REVIEW

**Comment by GalaxyGorilla** [comment]
I _really_ want this!

**Comment by mediafreakch** [comment]
@pruser Any chance this can be merged?

**Comment by pruser** [comment]
@mediafreakch I hope so, but we should ask @danielgtaylor instead.

**Comment by danielgtaylor** [comment]
I like this a lot, thanks! I'm reviewing it now and will throw some of my OpenAPI docs at it to test.

**Pull request merged**
