### PR TITLE
add flag to reload spec on every request

### PR DESCRIPTION
**Pull request by Lidbetter**
This change aims to improve the experience while writing api consumer code and testing against an evolving api spec, without restarting the apisprout server.

Parameter added: `reparse-on-request`

When a request comes in, and the parameter flag is enabled, the spec is reloaded from file/refetched from the url and reparsed.

### CODE REVIEW

**Comment by Lidbetter** [comment]
This maybe the entirely wrong approach - I am not yet very experienced working in Go. I am very happy to make changes if you can provide some guidance as to what you would like to see.

**Comment by danielgtaylor** [comment]
I like the idea behind this PR. What about using a file path watcher? These are OS-specific but libraries should exist to handle it that we can hook into. Then we only reload the file when it has actually changed rather than on every request.

**Comment by danielgtaylor** [comment]
This would likely do what we need: https://github.com/fsnotify/fsnotify

**Comment by danielgtaylor** [comment]
@Lidbetter please take a look at the implementation in  92d4f7889b7e6b0a08d3875daa44a68f5acd97bd, which uses the `fsnotify` package.

**Comment by Lidbetter** [comment]
Nice I was going to take a look this weekend, but you beat me to it.
Looks good, thanks

**Pull request closed without merging**
